name: Upload Preview To Azure Blob Storage
on: 
  push:
    branches: 
      - 'master'
    paths:
      - 'www/**'
        
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: www
          container_name: $web
          connection_string: DefaultEndpointsProtocol=https;AccountName=normalatordotcom;AccountKey=CNRZTQL6Dja/DoqgMtHPGq1Q30qNYh2cWdM3dNYaicpbgfVIPzvPDhP+9ZIimIoYABh+D369nRdP728BnJ/U4w==;EndpointSuffix=core.windows.net
          extra_args: ''
